name: Build-Test-Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use .NET Core sdk
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'  # Update with your desired .NET version

    - name: Restore dependencies using dotnet restore
      run: dotnet restore

    - name: Run tests
      run: dotnet test

    - name: Build and publish
      run: dotnet publish -c Release -o out

    - name: Login to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mysuperservice-image:latest . 

    - name: Push Docker image to registry
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mysuperservice-image:latest

  deploy-to-local:  # This job is for demo purposes only
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@v3

    - name: Run the container (local)
      run: docker run -d -p 5000:80 ${{ secrets.DOCKER_HUB_USERNAME }}/mysuperservice-image:latest
